### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by chrisduerr** [RazrFalcon/pangocairo-rs#11]
There are a couple of `Use of undeclared type or module` errors in `src/font_map.rs`.

Full build log:
https://hastebin.com/ijayoyesuv

**Comment by RazrFalcon** [comment]
What version did you use: git or from crates?

**Comment by chrisduerr** [comment]
I used the latest git version. When pulling from git (so without target or `Cargo.lock`) and trying to build, it fails for me.

**Comment by RazrFalcon** [comment]
Confirmed. Will fix it soon.

**Comment by chrisduerr** [comment]
I appreciate the quick response :+1:

**Comment by RazrFalcon** [comment]
Should be fixed now.
