### ISSUE TITLE
impossible to build

### ISSUE THREAD

**Issue by charlesvdv** [RazrFalcon/pangocairo-rs#9]
Hi!

Since 532494fde8c4296b232582e23a28498adb5486a1, it's impossible to build to project. Resetting ```libc = "0.2.22``` fix the problem. Here is the error message:
```
➜ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to select a version for `libc` (required by `pangocairo-sys`):
all possible versions conflict with previously selected versions of `libc`
  version 0.2.22 in use by libc v0.2.22
  possible versions to select: 0.2.20
```

**Comment by RazrFalcon** [comment]
What exactly do you building? master? `create` branch? From crates?

**Comment by charlesvdv** [comment]
The master from git.

**Comment by RazrFalcon** [comment]
Works fine for me. What OS do you use?

**Comment by charlesvdv** [comment]
I'm using Linux

**Comment by mjkillough** [comment]
FWIW, it works fine for me on Linux, as of 532494fde8c4296b232582e23a28498adb5486a1.

**Comment by johncf** [comment]
I think the problem is due to [specifying the patch version](https://github.com/RazrFalcon/pangocairo-rs/blob/532494f/pangocairo-sys/Cargo.toml#L15) in `pangocairo-sys`. It's better to [leave that out](https://github.com/gtk-rs/sys/blob/master/gtk-sys/Cargo.toml#L6), so that cargo can select the latest version all crates agrees upon.

**Comment by RazrFalcon** [comment]
@johncf I've added a specific version because I've got version mismatch errors.

**Comment by johncf** [comment]
@RazrFalcon Not sure how that is possible. (I can't claim I understand version resolution too well.) But did you do `cargo update` before doing `cargo build`? Perhaps it is due to a stale `Cargo.lock`?

**Comment by RazrFalcon** [comment]
Strange. It works now. 

@charlesvdv try latest master.

**Comment by mjkillough** [comment]
When adding `pangociaro` as a dep in my existing project (which already had a dependency on `cairo-rs`) I bumped into this. I think `cairo-rs` had previously selected 0.2.22 and placed it in `Cargo.lock`, so when `pangocairo` later asks for the exact version 0.2.20, Cargo can't resolve it. Removing my `Cargo.lock` and doing a clean build fixed the issue for me.

If you don't need to pin the version to 0.2.20, that's even better!

**Comment by charlesvdv** [comment]
I just tried to compile with a fresh `git clone` of the project and it works without problem now.

**Comment by RazrFalcon** [comment]
Good.
